services:
  d1_arm_bridge:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: go2w_d1_arm:humble
    container_name: go2w_d1_arm
    network_mode: host
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      ROS_NETWORK_INTERFACE: ${ROS_NETWORK_INTERFACE:-wlan0}
      CYCLONEDDS_URI: ${CYCLONEDDS_URI:-}
      UNITREE_NETWORK_INTERFACE: ${UNITREE_NETWORK_INTERFACE:-eth0}
    command: ["/start_bridge.sh"]
    stdin_open: true
    tty: true
    restart: "no"
